---
shortname: UAI
booktitle: Proceedings of the Forty-first Conference on Uncertainty in Artificial
  Intelligence
year: '2025'
start: &1 2025-07-21
end: 2025-07-25
published: 2025-07-11
volume: '286'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: UAI2025
month: 0
cycles: false
bibtex_editor: Chiappa, Silvia and Magliacane, Sara
editor:
- given: Silvia
  family: Chiappa
- given: Sara
  family: Magliacane
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Forty-first Conference on Uncertainty in Artificial Intelligence
    Held in Rio Othon Palace, Rio de Janeiro, Brazil on 21-25 July 2025

  Published as Volume 286 by the Proceedings of Machine Learning Research on 11 July 2025.

  Volume Edited by:
    Silvia Chiappa
    Sara Magliacane

  Series Editors:
    Neil D. Lawrence
date_str: 21--25 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v286"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v286
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v286
email: ''
conference:
  name: Conference on Uncertainty in Artificial Intelligence
  url: https://www.auai.org/uai2025/
  location: Rio Othon Palace, Rio de Janeiro, Brazil
  dates:
  - *1
  - 2025-07-22
  - 2025-07-23
  - 2025-07-24
  - 2025-07-25
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: uai2025_clean.bib
# Site settings
# Original source:  uai2025_clean.bib
